apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  description: tns
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
