apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-instrumentation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: tns
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://github.com/grzesiek2115/MyPlatform.git
    targetRevision: HEAD
    path: argocd/opentelemetry/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
