apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: 4.1.5
    helm:
      values: |
        cluster:
          name: kind-myplatform

        destinations:
          prometheus:
            type: prometheus
            url: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write
          loki:
            type: loki
            url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
          tempo:
            type: otlp
            url: http://tempo.tempo.svc.cluster.local:4317

        clusterMetrics:
          enabled: true
          collector: alloy-singleton

        hostMetrics:
          enabled: true
          collector: alloy-metrics
          energyMetrics:
            enabled: true

        costMetrics:
          enabled: true
          collector: alloy-singleton

        annotationAutodiscovery:
          enabled: true
          collector: alloy-metrics

        prometheusOperatorObjects:
          enabled: true
          collector: alloy-metrics

        integrations:
          enabled: true
          collector: alloy-metrics

        clusterEvents:
          enabled: true
          collector: alloy-singleton

        nodeLogs:
          enabled: true
          collector: alloy-logs

        podLogsViaLoki:
          enabled: true
          collector: alloy-logs

        podLogsViaOpenTelemetry:
          enabled: false

        podLogsObjects:
          enabled: true
          collector: alloy-logs

        podLogsViaKubernetesApi:
          enabled: false

        applicationObservability:
          enabled: false

        autoInstrumentation:
          enabled: false

        profiling:
          enabled: true
          collector: alloy-profiles

        profilesReceiver:
          enabled: true
          collector: alloy-profiles

        collectors:
          alloy-metrics:
            enabled: true
            alloy:
              clustering:
                enabled: true
          alloy-logs:
            enabled: true
            alloy:
              mounts:
                varlog: false
              clustering:
                enabled: true
          alloy-singleton:
            enabled: true
            alloy:
              clustering:
                enabled: true
          alloy-profiles:
            enabled: true
            alloy:
              clustering:
                enabled: true
          alloy-receiver:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
