apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.2.2
    helm:
      values: |
        grafana:
          enabled: false

        prometheus:
          prometheusSpec:
            enableRemoteWriteReceiver: true
            retention: 7d
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi

        alertmanager:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
