apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
spec:
  destination:
    namespace: pyroscope
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: pyroscope
    targetRevision: 2.0.3
    helm:
      values: |
        pyroscope:
          replicaCount: 1
          persistence:
            enabled: true
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

        alloy:
          enabled: false

        minio:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
