apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
spec:
  destination:
    namespace: pyroscope
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: pyroscope
    targetRevision: 2.0.3
    helm:
      values: |
        pyroscope:
          replicationFactor: 1
          components:
            querier:
              replicas: 1
            queryFrontend:
              replicas: 1
            distributor:
              replicas: 1
            ingester:
              replicas: 1

        alloy:
          enabled: false

        storage:
          backend: filesystem
          filesystem:
            dir: /data/pyroscope

        persistence:
          enabled: true
          size: 5Gi

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
