apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sloth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://slok.github.io/sloth
    chart: sloth
    targetRevision: 0.16.0
    helm:
      values: |
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
