apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    repoURL: https://github.com/grzesiek2115/MyPlatform.git
    targetRevision: main
    path: argocd/slo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
