apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default
  namespace: tns
spec:
  exporter:
    endpoint: http://tempo.tempo.svc.cluster.local:4317

  propagators:
    - tracecontext
    - baggage
    - b3

  sampler:
    type: parentbased_traceidratio
    argument: "1.0"

  go:
    env:
      - name: OTEL_GO_AUTO_TARGET_EXE
        value: /app/tns-app
